### ISSUE TITLE
这就是MIT协议开源项目吗 爱了爱了

### ISSUE THREAD

**Issue by RubyXun** [weizhiqiang1995/skyeye#14]
这就是MIT协议开源项目吗 爱了爱了==

**Comment by feihong247** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by weizhiqiang1995** [comment]
开源也是需要精力和时间来维护的，并且这个项目并不仅仅是一个低代码框架，更是一整套企业级的项目
